# 默认训练配置

lr: 0.001 # 学习率
lr_end_factor: 0.01 # 学习率结束因子
freeze_backbone: True  # 是否冻结骨干网络
unfrozen_names: [ # 未冻结的骨干网络参数
            # "blocks.11.norm1.weight",
            # "blocks.11.norm1.bias",
            # "blocks.11.attn.qkv.weight",
            # "blocks.11.attn.qkv.bias",
            # "blocks.11.attn.proj.weight",
            # "blocks.11.attn.proj.bias",
            # "blocks.11.ls1.gamma",
            # "blocks.11.norm2.weight",
            # "blocks.11.norm2.bias",
            # "blocks.11.mlp.fc1.weight",
            # "blocks.11.mlp.fc1.bias",
            # "blocks.11.mlp.fc2.weight",
            # "blocks.11.mlp.fc2.bias",
            # "blocks.11.ls2.gamma",
            # "blocks.8",
            # "blocks.9",
            # "blocks.10",
            "blocks.11",
            "norm.weight",
            "norm.bias"
]
# 参数组配置
param_groups:
  - regex: "backbone.*"   # 匹配所有backbone相关参数
    lr: 0.00001
  - regex: "head.*"       # 匹配所有head相关参数
    lr: 0.001
dropout_p: 0.2

max_epochs: 50 # 最大训练轮数
batch_size: 64 # 批次大小
num_workers: 12 # 数据加载线程数

# 数据集配置
# dataset:
#   val_path: "/root/autodl-tmp/seat_dataset/chengdu_customer"
#   train_path: "/root/autodl-tmp/seat_dataset/chengdu_valid/"
#   val_ann: "/root/autodl-tmp/seat_dataset/chengdu_customer/_classification.coco.json"
#   train_ann: "/root/autodl-tmp/seat_dataset/chengdu_valid/_classification.coco.json"
dataset:
  train_path: "/root/autodl-tmp/seat_dataset/chengdu_resplit-21/train"
  val_path: "/root/autodl-tmp/seat_dataset/chengdu_resplit-21/valid"
  train_ann: "/root/autodl-tmp/seat_dataset/chengdu_resplit-21/train/_classification.coco.json"
  val_ann: "/root/autodl-tmp/seat_dataset/chengdu_resplit-21/valid/_classification.coco.json"
# target_category_names: ["褶皱（重度）", "划伤"]
target_category_names: ["褶皱（重度）"]
# target_category_names: ['其他', '划伤', '压痕', '异物外漏', '折痕', '抛线', '拼接间隙', '水渍', '破损', '碰伤', '红标签', '线头', '脏污', '褶皱(T型)', '褶皱（重度）', '重跳针']
iou_threshold: 0.5
merge_coco_dict:
  # 缺陷: ['其他', '划伤', '压痕', '异物外漏', '折痕', '抛线', '拼接间隙', '水渍', '破损', '碰伤', '红标签', '线头', '脏污', '褶皱(T型)', '褶皱（重度）', '重跳针']
  NG: ['褶皱（重度）']
  OK: ["背景"]

only_keep_predict: True # 只保留预测(predict)来源的标注

# 是否重新划分数据集
re_split: False
# 重新划分数据集的训练集比例
train_ratio: 0.8

# 数据预处理参数
min_bbox_area: 0  # 最小标注框面积
crop_scale_factor: 1.5  # 裁剪范围因子

resize:
  width: 224
  height: 224

pad_mode: "constant"  # 越界填充方式 ("constant", "edge", None)
pad_color: [0,0,0]  # 常数填充的颜色 (R, G, B)

# 模型配置
backbone_weights: "/root/autodl-tmp/seat_model/dinov3/dinov3_vitb16_pretrain_lvd1689m-73cec8be.pth"

with_detection_feature: True