# 默认训练配置
# 学习率
lr: 0.0001

# 训练参数
max_epochs: 30
batch_size: 64
num_workers: 12
num_classes: 2

# 数据集配置
dataset:
  train_path: "/root/autodl-tmp/seat_dataset/chengdu_customer"
  val_path: "/root/autodl-tmp/seat_dataset/chengdu_valid/"
  train_ann: "/root/autodl-tmp/seat_dataset/chengdu_customer/_classification.coco.json"
  val_ann: "/root/autodl-tmp/seat_dataset/chengdu_valid/_classification.coco.json"
target_category_names: ["褶皱"]
iou_threshold: 0.4
merge_coco_dict: None

# 数据预处理参数
min_bbox_area: 900

# 模型配置
backbone_weights: "/root/autodl-tmp/seat_model/dinov3/dinov3_vitb16_pretrain_lvd1689m-73cec8be.pth"
